name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  - push
  - workflow_dispatch

jobs:
  set-version:
    name: Set variables
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: "Set version"
        id: constants
        run: |
          export version="1.$(date +%Y%m%d%H%M%S).0+$(git describe --always --dirty --exclude '*')"
          echo "version=${version}"
          echo "version=${version}" >> ${GITHUB_OUTPUT}
    outputs:
      version: "${{ steps.constants.outputs.version }}"
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - set-version
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3
      - name: Run checks
        run: mise run checks
      - name: Inject version into files
        run: mise run inject-version "${{ needs.set-version.outputs.version }}"
      - name: Build zipfile
        run: mise run build-zip "${{ needs.set-version.outputs.version }}"
      - name: Save zipfile for release
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: zipfile
          path: ark-metadata-${{ needs.set-version.outputs.version }}.zip
          if-no-files-found: error
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    needs:
      - set-version
      - build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: zipfile
      - name: create release
        id: create_release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          tag_name: ${{ needs.set-version.outputs.version }}
          name: Release ${{ needs.set-version.outputs.version }}
          draft: false
          prerelease: false
          files: ark-metadata-${{ needs.set-version.outputs.version }}.zip
